name: mlfow-env
channels:
  - conda-forge
  - nvidia
  - pytorch
  - nodefaults
dependencies:
  - python=3.11
  - conda-forge::packaging
  - conda-forge::ninja
  - pip
  - pip:
    - --extra-index-url https://download.pytorch.org/whl/cu121
    - torch==2.3.1+cu121
    - torchvision==0.18.1+cu121
    - mlflow==2.15.1
    - cloudpickle==2.2.1
    - /model/artifacts/dbboltz[gpu]