name: mlfow-env
channels:
  - conda-forge
  - nvidia
  - nodefaults
dependencies:
  - python=3.10
  - nvidia::cudatoolkit=11.3
  - pip
  - pip:
    - --extra-index-url https://download.pytorch.org/whl/cu113
    - torch==1.11.0+cu113
    - torchvision==0.12.0+cu113
    - torchaudio==0.11.0
    - mlflow==2.15.1
    - cloudpickle==2.2.1
    - biopython==1.79
    - /model/artifacts/proteinmpnn